##
# Copyrights:  2025 Codoworks.com
# Author:      Dexter Codo
# Website:     https://dexterexplains.com 
# Contact:     hello@dexterexplains.com
# Project:     Kubernetes Installer
##

# PLAYBOOK CONFIG ----------------------------------------------------------------------------
- hosts: initializing_master_node
  become: true
  gather_facts: true

  # VAR PROMPTS ------------------------------------------------------------------------------

  # vars_prompt:
  #  - name: "var_name"
  #    prompt: "User prompt? change me..."
  #    private: false # should this be visible or hidden like a password
     
  # TASKS ------------------------------------------------------------------------------------
  tasks: 
  # PRE-FLIGHT CHECKS ------------------------------------------------------------------------
  - name: Pre-flight check, fail if OS is not Ubuntu.
    when: ansible_distribution != "Ubuntu" and ansible_distribution != "RedHat"
    fail:
      msg: "This script is designed for Ubuntu"

  # PRE-CONFIG -------------------------------------------------------------------------------
  - name: Whoami on the node?
    become: false
    shell: whoami
    register: node_username_raw

  - name: Set whoami on the node as a fact.
    set_fact:
      node_username: "{{ node_username_raw.stdout_lines[0] }}"

  # BEGIN ------------------------------------------------------------------------------------
  - name: Add Nginx Helm Repo
    become: false
    shell: helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx

  - name: Update Helm Repo
    become: false
    shell: helm repo update

  - name: Pull nginx helm chart
    become: false
    shell: helm pull ingress-nginx/ingress-nginx --version {{ nginx_version }} --untar
    args:
      chdir: "/home/{{ node_username }}/helm-charts"

  - name: Update config nginx helm chart
    when: use_metallb == false and ansible_distribution == "Ubuntu"
    become: false
    shell: |
      yq -yi '.controller.kind = "DaemonSet"' helm-charts/ingress-nginx/values.yaml
      yq -yi '.controller.service.type = "LoadBalancer' helm-charts/ingress-nginx/values.yaml
      yq -yi '.controller.service.externalIPs += {{ worker_ips | to_nice_json }}' helm-charts/ingress-nginx/values.yaml

    vars:
      worker_ips: "{{ groups['worker_nodes'] | map('extract', hostvars, 'inventory_hostname') | list }}"

  - name: Update config nginx helm chart
    when: use_metallb == false and ansible_distribution == "RedHat"
    become: false
    shell: |
      yq -i '.controller.kind = "DaemonSet"' helm-charts/ingress-nginx/values.yaml
      yq -i '.controller.service.type = "LoadBalancer' helm-charts/ingress-nginx/values.yaml
      yq -i '.controller.service.externalIPs += {{ worker_ips | to_nice_json }}' helm-charts/ingress-nginx/values.yaml
      
    vars:
      worker_ips: "{{ groups['worker_nodes'] | map('extract', hostvars, 'inventory_hostname') | list }}"

  - name: Update config nginx helm chart
    when: use_metallb == true and ansible_distribution == "Ubuntu"
    become: false
    shell: |
      yq -yi '.controller.kind = "DaemonSet"' helm-charts/ingress-nginx/values.yaml
      yq -yi '.controller.service.type = "LoadBalancer' helm-charts/ingress-nginx/values.yaml

  - name: Update config nginx helm chart
    when: use_metallb == true and ansible_distribution == "RedHat"
    become: false
    shell: |
      yq -i '.controller.kind = "DaemonSet"' helm-charts/ingress-nginx/values.yaml
      yq -i '.controller.service.type = "LoadBalancer' helm-charts/ingress-nginx/values.yaml

  - name: Install nginx helm chart
    become: false
    shell: helm install nginx ./helm-charts/ingress-nginx --namespace nginx --create-namespace --values ./helm-charts/ingress-nginx/values.yaml
      
  # CLEAN UP ---------------------------------------------------------------------------------